#!/bin/sh
 
# Base Variables

ORACLE_BASE="/opt/oracle"
export ORACLE_BASE

ORACLE_INVENTORY_HOME="${ORACLE_BASE}/oraInventory"
export ORACLE_INVENTORY_HOME

ORACLE_INVENTORY_PTR="/etc/oraInst.loc"
export ORACLE_INVENTORY_PTR

# Staging Variables

STAGING_DIRECTORY="/opt/software"
export STAGING_DIRECTORY

# BB Variables

TARGET_ENVIRONMENT="lab"
export TARGET_ENVIRONMENT

FUNCTIONAL_BLOCK_NAME="ohs01"
export FUNCTIONAL_BLOCK_NAME

BUILDING_BLOCK_NAME="ohs01"
export BUILDING_BLOCK_NAME

BB_FULL_NAME="${TARGET_ENVIRONMENT}_${FUNCTIONAL_BLOCK_NAME}_${BUILDING_BLOCK_NAME}"
export BB_FULL_NAME

BUILDING_BLOCK_VERSION="12.2"
export BUILDING_BLOCK_VERSION

BUILDING_BLOCK_HOME="${ORACLE_BASE}/${FUNCTIONAL_BLOCK_NAME}/${BUILDING_BLOCK_NAME}/${BUILDING_BLOCK_VERSION}"
export BUILDING_BLOCK_HOME

BUILDING_BLOCK_USER="oracle"
export BUILDING_BLOCK_USER

BUILDING_BLOCK_GROUP="oinstall"
export BUILDING_BLOCK_GROUP


# Available types:
#     INFRA : Infrastructure
#     SOA   : SOA Suite
#     OSB   : Service BUS
#     BAM   : Business Analytic
#     BPM   : Business Process
#     OHS   : Oracle HTTP Server

INSTALL_TYPE='OHS'
export INSTALL_TYPE

# FMW Variables

MIDDLEWARE_HOME="${BUILDING_BLOCK_HOME}/fmw"
export MIDDLEWARE_HOME
